---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: purelb
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: acnodal
      addresses:
      - 0.0.0.0-255.255.255.255
