image: docker:latest
services:
  - docker:dind
variables:
  ALLOCATOR_IMG: $CI_REGISTRY_IMAGE/allocator
  LBNODEAGENT_IMG: $CI_REGISTRY_IMAGE/lbnodeagent
  NETBOX_USER_TOKEN: no-op
  # https://docs.gitlab.com/12.10/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_TLS_CERTDIR: "/certs"
before_script:
- apk add make
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - image
  - manifest
  - test

format:
  stage: test
  image: golang:latest
  before_script: []
  script:
    - make deployments/purelb-complete.yaml check
  artifacts:
    paths:
      - deployments/purelb-complete.yaml

allocatorarm:
  stage: image
  tags:
  - arm
  script: make SUFFIX=arm-ci image-allocator install-allocator

allocatoramd:
  stage: image
  script: make SUFFIX=amd64-ci image-allocator install-allocator

lbnodeagentarm:
  stage: image
  tags:
  - arm
  script: make SUFFIX=arm-ci image-lbnodeagent install-lbnodeagent

lbnodeagentamd:
  stage: image
  script: make SUFFIX=amd64-ci image-lbnodeagent install-lbnodeagent

manifest:
  stage: manifest
  script:
    - docker manifest create $ALLOCATOR_IMG:ci $ALLOCATOR_IMG:amd64-ci $ALLOCATOR_IMG:arm-ci
    - docker manifest push $ALLOCATOR_IMG:ci
    - docker manifest create $LBNODEAGENT_IMG:ci $LBNODEAGENT_IMG:amd64-ci $LBNODEAGENT_IMG:arm-ci
    - docker manifest push $LBNODEAGENT_IMG:ci
