image: docker:latest
services:
  - docker:dind
variables:
  ALLOCATOR_IMG: $CI_REGISTRY_IMAGE/allocator
  LBNODEAGENT_IMG: $CI_REGISTRY_IMAGE/lbnodeagent
  NETBOX_USER_TOKEN: no-op
  # https://docs.gitlab.com/12.10/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_TLS_CERTDIR: "/certs"
before_script:
- apk add make git
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
- mkdir -p ~/.ssh && chmod 700 ~/.ssh
- ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

stages:
  - test
  - image
  - manifest

check:
  stage: test
  image: golang:latest
  services: []
  before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
  script: make check

allocatorarm64:
  stage: image
  tags:
  - arm64
  script: make SUFFIX=arm64-ci image-allocator install-allocator

allocatoramd:
  stage: image
  script: make SUFFIX=amd64-ci image-allocator install-allocator

lbnodeagentarm64:
  stage: image
  tags:
  - arm64
  script: make SUFFIX=arm64-ci image-lbnodeagent install-lbnodeagent

lbnodeagentamd:
  stage: image
  script: make SUFFIX=amd64-ci image-lbnodeagent install-lbnodeagent

manifest:
  stage: manifest
  script:
    - docker manifest create $ALLOCATOR_IMG:ci $ALLOCATOR_IMG:amd64-ci $ALLOCATOR_IMG:arm64-ci
    - docker manifest push $ALLOCATOR_IMG:ci
    - docker manifest create $LBNODEAGENT_IMG:ci $LBNODEAGENT_IMG:amd64-ci $LBNODEAGENT_IMG:arm64-ci
    - docker manifest push $LBNODEAGENT_IMG:ci
    - make generate-manifest
  artifacts:
    paths:
      - deployments/purelb-complete.yaml
