image: docker:20.10.3
services:
  - docker:20.10.3-dind
variables:
  PROJECT: $CI_PROJECT_NAME
  ALLOCATOR_IMG: $CI_REGISTRY_IMAGE/allocator
  LBNODEAGENT_IMG: $CI_REGISTRY_IMAGE/lbnodeagent
  TAG_SPECIFIC: ci-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  TAG_LATEST: ci-${CI_COMMIT_REF_SLUG}-latest
  NETBOX_USER_TOKEN: no-op
  # https://docs.gitlab.com/12.10/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_TLS_CERTDIR: "/certs"
before_script:
- apk add make git
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
- mkdir -p ~/.ssh && chmod 700 ~/.ssh
- ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

stages:
  - test
  - image
  - manifest

check:
  stage: test
  image: golang:1.15.8-buster
  services: []
  before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
  script: make check

allocatoramd:
  stage: image
  script: make SUFFIX=amd64-${TAG_SPECIFIC} image-allocator install-allocator

lbnodeagentamd:
  stage: image
  script: make SUFFIX=amd64-${TAG_SPECIFIC} image-lbnodeagent install-lbnodeagent

manifest:
  stage: manifest
  script:
    - wget --quiet -O - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.0.1/kustomize_v4.0.1_linux_amd64.tar.gz | tar -C /usr/local/bin -xzf -
    - make REGISTRY_IMAGE=${CI_REGISTRY_IMAGE} MANIFEST_SUFFIX=${TAG_SPECIFIC} SUFFIX=${TAG_SPECIFIC} manifest docker-manifest
    - make REGISTRY_IMAGE=${CI_REGISTRY_IMAGE} MANIFEST_SUFFIX=${TAG_LATEST} SUFFIX=${TAG_LATEST} manifest
    - make REGISTRY_IMAGE=${CI_REGISTRY_IMAGE} MANIFEST_SUFFIX=${TAG_LATEST} SUFFIX=${TAG_SPECIFIC} docker-manifest

  artifacts:
    paths:
      - deployments/*
      - configs/*
