image: golang:latest
services:
  - docker:dind
variables:
  ALLOCATOR_IMG: $CI_REGISTRY_IMAGE/allocator
  LBNODEAGENT_IMG: $CI_REGISTRY_IMAGE/lbnodeagent
  NETBOX_USER_TOKEN: no-op
  # https://docs.gitlab.com/12.10/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - image
  - manifest
  - test

format:
  stage: test
  script:
    - make deployments/purelb-complete.yaml check
  artifacts:
    paths:
      - deployments/purelb-complete.yaml

allocatorarm:
  stage: image
  image: docker:latest
  tags:
  - arm
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f build/package/Dockerfile.allocator --build-arg opts="GOARCH=arm" --build-arg cmd=allocator --build-arg branch=$CI_COMMIT_REF_NAME --build-arg commit=$CI_COMMIT_TAG --pull -t $ALLOCATOR_IMG:arm-ci .
    - docker push $ALLOCATOR_IMG:arm-ci

allocatoramd:
  stage: image
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f build/package/Dockerfile.allocator --build-arg opts="GOARCH=amd64 CGO_ENABLED=0" --build-arg cmd=allocator --build-arg branch=$CI_COMMIT_REF_NAME --build-arg commit=$CI_COMMIT_TAG --pull -t $ALLOCATOR_IMG:amd64-ci .
    - docker push $ALLOCATOR_IMG:amd64-ci

lbnodeagentarm:
  stage: image
  image: docker:latest
  tags:
  - arm
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f build/package/Dockerfile.lbnodeagent --build-arg opts="GOARCH=arm" --build-arg cmd=lbnodeagent --build-arg branch=$CI_COMMIT_REF_NAME --build-arg commit=$CI_COMMIT_TAG --pull -t $LBNODEAGENT_IMG:arm-ci .
    - docker push $LBNODEAGENT_IMG:arm-ci

lbnodeagentamd:
  stage: image
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f build/package/Dockerfile.lbnodeagent --build-arg opts="GOARCH=amd64 CGO_ENABLED=0" --build-arg cmd=lbnodeagent --build-arg branch=$CI_COMMIT_REF_NAME --build-arg commit=$CI_COMMIT_TAG --pull -t $LBNODEAGENT_IMG:amd64-ci .
    - docker push $LBNODEAGENT_IMG:amd64-ci

manifest:
  stage: manifest
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker manifest create $ALLOCATOR_IMG:ci $ALLOCATOR_IMG:amd64-ci $ALLOCATOR_IMG:arm-ci
    - docker manifest push $ALLOCATOR_IMG:ci
    - docker manifest create $LBNODEAGENT_IMG:ci $LBNODEAGENT_IMG:amd64-ci $LBNODEAGENT_IMG:arm-ci
    - docker manifest push $LBNODEAGENT_IMG:ci
