---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: purelb
  name: lbnodeagent
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: purelb
  name: allocator
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitlab
