---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: purelb
  name: lbnodeagent
spec:
  template:
    spec:
      hostAliases:
      - ip: EPIC_CTL_IP
        hostnames:
        - epic-ctl
      - ip: 172.30.66.1
        hostnames:
        - epic-1-ctl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: purelb
  name: allocator
spec:
  template:
    spec:
      hostAliases:
      - ip: EPIC_CTL_IP
        hostnames:
        - epic-ctl
      - ip: 172.30.66.1
        hostnames:
        - epic-1-ctl
