---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lbnodeagents.purelb.io
spec:
  group: purelb.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              oneOf:
              - required: ["local"]
              - required: ["epic"]
              properties:
                local:
                  type: object
                  properties:
                    localint:
                      type: string
                      default: "default"
                    extlbint:
                      type: string
                      default: "kube-lb0"
                epic:
                  type: object
                  properties:
                    decapAttachment:
                      type: object
                      properties:
                        direction:
                          type: string
                          default: "ingress"
                        flags:
                          type: integer
                          default: 1
                        interface:
                          type: string
                          default: "default"
                        qid:
                          type: integer
                          default: 0
                    encapAttachment:
                      type: object
                      properties:
                        direction:
                          type: string
                          default: "egress"
                        flags:
                          type: integer
                          default: 16
                        interface:
                          type: string
                          default: "default"
                        qid:
                          type: integer
                          default: 1
  scope: Namespaced
  names:
    plural: lbnodeagents
    singular: lbnodeagent
    kind: LBNodeAgent
    shortNames:
    - lbna
    categories:
    - all
