apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicegroups.purelb.io
spec:
  group: purelb.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                subnetv4:
                  type: string
                poolv4:
                  type: string
                aggregation:
                  type: string
            status:
              type: object
              properties:
                allocated:
                  type: integer
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: servicegroups
    singular: servicegroup
    kind: ServiceGroup
    shortNames:
    - sg
    categories:
    - all