---
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    subnet: '192.168.254.100/24'
    pool: '192.168.254.200-192.168.254.201'
    aggregation: default
